blueprint:
  name: Disable activated switch 
  description: Turn off a swtich after a periode of time
  domain: automation
  input:
    activated_entity:
      name: Switch
      selector: 
        entity:
          domain: binary_sensor
    switch_target:
      name: Switch
      selector:
        target:
          entity:
            domain: switch
    no_motion_wait:
      name: Wait time
      description: Time till the turns off after is switched on.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

trigger:
  - platform: state
    entity_id: !input activated_entity
    from: "off"
    to: "on"

action:
  - service: switch.turn_on
    target: !input switch_target
  - wait_for_trigger:
      platform: state
      entity_id: !input activated_entity
      from: "on"
      to: "off"
  - delay: !input no_motion_wait
  - service: switch.turn_off
    target: !input switch_target